# mkdir grafana_on_port_(port)

version: '3.9'
services:
  app:
    image: 'msupplyfoundation/conforma-demo:${TAG}'
    ports:
      - '${PORT_APP}:3000'
    expose:
      - '5432'
    environment:
      SMTP_PASSWORD: '${SMTP_SECRET}'
      WEB_HOST: '${WEB_URL}'
      JWT_SECRET: '${JWT_SECRET}'
    volumes:
      - ./conforma_on_port_${PORT_APP}/postgres:/var/lib/postgresql/12/main/
      - ./conforma_on_port_${PORT_APP}/snapshots:/usr/src/application-manager-server/build/database/_snapshots
      - ./conforma_on_port_${PORT_APP}/files:/usr/src/application-manager-server/build/files
      - ./conforma_on_port_${PORT_APP}/localisation:/usr/src/application-manager-server/build/localisations
      - ./conforma_on_port_${PORT_APP}/preferences:/usr/src/application-manager-server/build/preferences
    tty: true
  grafana:
    image: 'grafana/grafana'
    ports:
      - '${PORT_DASH}:3000'
    volumes:
      - ./grafana_on_port_${PORT_DASH}:/var/lib/grafana
