-- template element (questions or information elements)
CREATE TYPE public.template_element_category AS ENUM (
    'QUESTION',
    'INFORMATION'
);

CREATE TYPE public.reviewability AS ENUM (
    'ALWAYS',
    'NEVER',
    'ONLY_IF_APPLICANT_ANSWER',
    'OPTIONAL_IF_NO_RESPONSE'
    -- TO-DO:
    -- 'OPTIONAL_IF_RESPONSE',
    -- 'OPTIONAL' (the above two combined)
);

CREATE TABLE public.template_element (
    id serial PRIMARY KEY,
    section_id integer REFERENCES public.template_section (id) ON DELETE CASCADE NOT NULL,
    code varchar NOT NULL,
    index integer,
    title varchar,
    category public.template_element_category,
    element_type_plugin_code varchar,
    visibility_condition jsonb DEFAULT 'true' ::jsonb,
    is_required jsonb DEFAULT 'true' ::jsonb,
    is_editable jsonb DEFAULT 'true' ::jsonb,
    validation jsonb DEFAULT 'true' ::jsonb,
    default_value jsonb,
    validation_message varchar,
    help_text varchar,
    parameters jsonb,
    reviewability public.reviewability DEFAULT 'ONLY_IF_APPLICANT_ANSWER' NOT NULL
    -- NOTE: There are more columns that get added to this table, but these are
    -- autogenerated using functions that are not yet defined, so have been
    -- added in the view_functions_triggers.sql script
);

