CREATE TABLE public.review (
    id serial PRIMARY KEY,
    review_assignment_id integer REFERENCES public.review_assignment (id) ON DELETE CASCADE,
    TRIGGER public.trigger
    -- NOTE: There are more columns that get added to the review table, but
    -- these are autogenerated using functions that are not yet defined, so have
    -- been added in the view_functions_triggers.sql script
);

